# problem 1

In [3]:
import numpy as nm
arr=nm.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## problem 2

In [5]:
import numpy as nm
list1,list2=[],[]
print("list items")
for i in range(5):
    t=int(input())
    list1.append(t)
print("list items")
for i in range(5):
    t=int(input())
    list2.append(t)
arr=nm.array([list1,list2])
print(arr)
print()
arr=arr.reshape(1,10)
arr=nm.sort(arr)
arr=arr.reshape(2,5)
print(arr)

list items
45699
4586
5614
4
35
list items
25
41
658
456
52
[[45699  4586  5614     4    35]
 [   25    41   658   456    52]]

[[    4    25    35    41    52]
 [  456   658  4586  5614 45699]]


### problem 3

In [6]:
import numpy as np
arr=np.array([[1,2,8],[6,3,7]])
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


#### problem 4

In [7]:
import numpy as np
arr=np.array([1,2,8,4])
print(arr)
print()
arr=arr.reshape(2,2)
print(arr)

[1 2 8 4]

[[1 2]
 [8 4]]


##### problem 5

In [8]:
import numpy as np 
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


###### problem 6

In [9]:

import numpy
number_list = numpy.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = numpy.unique(number_list, return_counts=True)
frequencies = numpy.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
